### ISSUE TITLE
finaliser la proposition   data.table French translation proposal.qmd

### ISSUE THREAD

**Issue by ChristianWia** [phgrosjean/rfrench#18]
fait pour ma part. N'hésitez pas à remettre en forme si cela ne convient pas.

Question:     qui répond à toby.hocking@r-project.org, ?
Si Philippe coordonne et centralise les demandes de candidature, il est préférable que toby.hocking n'ait qu'un seul interlocuteur et donc que chacun n'ait pas à contacter ce dernier individuellement.

 Avis ?   Merci.

**Comment by phgrosjean** [comment]
@ChristianWia @rochevin J'ai complété la demande et ai rajouté Elise comme contributrice à ce dépôt (invitation en cours). J'ai mis une phrase temporaire pour Elise dans le cas où elle ne souhaiterait pas demander d'award... mais comme pour vous deux, je l'encourage fortement à en demander un. Dès que l'on est tous les trois d'accord sur la version finale, j'enverra à Toby.

**Comment by ChristianWia** [comment]
ok vu.

**Comment by phgrosjean** [comment]
Je pense que l'on a une version finale maintenant.
