### ISSUE TITLE
base/po  TYPO source a corriger:   src/main/relop.c:185 "comparison (%s) is not possible language types"

### ISSUE THREAD

**Issue by ChristianWia** [phgrosjean/rfrench#20]
il manque un 'for' dans le fichier source : (voir dernier cas)

static SEXP compute_language_relop(SEXP call, SEXP op, SEXP x, SEXP y)
{
    static enum {...
	default:
	    errorcall(call,
		      _("comparison (%s) is not possible for language types"),
		      PRIMNAME(op));
	}
    case IDENTICAL_CALLS:....
	    errorcall(call,
		      _("comparison (%s) is not possible for language types"),
		      PRIMNAME(op));
	}
    case IDENTICAL_CALLS_ATTR:.....
		      _("comparison (%s) is not possible for language types"),
		      PRIMNAME(op));
	}
    case IDENTICAL:....
	default: errorcall(call,
			   _("comparison (%s) is not possible language types"),  **<<<** msgid "comparison (%s) is not possible **for** language types"
			   PRIMNAME(op));
	}....

**Comment by phgrosjean** [comment]
@ChristianWia Ah oui, effectivement. Il faudrait faire un rapport de bug au R Core Team. L'explication pour le faire est ici: https://www.r-project.org/bugs.html

**Comment by ChristianWia** [comment]
This is to remember a point to be raised to R team.

**Comment by ChristianWia** [comment]
Signalé -> https://bugs.r-project.org/show_bug.cgi?id=18797

**Comment by ChristianWia** [comment]
suivre l'historique du rapport de bogue
