### ISSUE TITLE
confirmation de traduction -> computationally singular,  matrix exactly singular,  nondecreasing vector

### ISSUE THREAD

**Issue by ChristianWia** [phgrosjean/rfrench#28]
Dans le fichier:      rfrench/Recommended/Matrix/po/R-fr.po

computationally singular -> matrice singulière par calcul

matrix is exactly singular -> matrice singulière exactement

a nondecreasing vector -> un vecteur de valeurs non décroissantes

Estce acceptable ?

**Comment by emaigne** [comment]
"matrice exactement singulière" me paraîtrait plus correct !

**Comment by ChristianWia** [comment]
computationally singular -> matrice singulière par calcul
matrix is exactly singular -> matrice exactement singulière 
a nondecreasing vector -> un vecteur de valeurs non décroissantes

adjugé - merci.

**Comment by ChristianWia** [comment]
statué.
