### ISSUE TITLE
2 lignes EN pareilles singulier/pluriel  dans library/tools/po /R-fr.po

### ISSUE THREAD

**Issue by ChristianWia** [phgrosjean/rfrench#32]
2 lignes pareilles singulier/pluriel dans le fichier source EN 4.4.0/src/library/tools/po /R-fr.po  ligne 1751:

msgid        "%d of the package tests failed"
msgid_plural "%d of the package tests failed"

Quel est l'intérêt ? Corriger le code s'il n'y a qu'une ligne ou différencier le texte pour lever l'ambiguité.

**Comment by phgrosjean** [comment]
@ChristianWia Il n'y a pas d'intérêt, sauf peut-être que les auteurs ont anticipé le fait que le message pourrait être modifié et devenir différent entre la forme singulier et la forme pluriel ?

**Comment by ChristianWia** [comment]
ok on fera remonter plutot que de jouer a deviner ce qui a changé (gain de temps pour les trducteurs).

**Comment by ChristianWia** [comment]
signalé et à suivre sur -> https://bugs.r-project.org/show_bug.cgi?id=18798
