### ISSUE TITLE
typo 'a.Internal' dans code source EN 4.4.0/src/library/tools/po /R-fr.po

### ISSUE THREAD

**Issue by ChristianWia** [phgrosjean/rfrench#33]
Dans  4.4.0/src/library/tools/po /R-fr.po ligne 1638  

msgid "Found a.Internal call in methods for the following S4 generic:"

est bizarre; il faudrait insérer un espace pour avoir 'Found a .Internal...' dans le code source pour être cohérent avec les messages suivants.

**Comment by phgrosjean** [comment]
@ChristianWia Oui, encore une fois, un petit rapport de bug au R Core Team, peut-être ?

**Comment by ChristianWia** [comment]
Je balaie tous les .po qui ont été proposés et on fera un tour des Issues à la fin en disant qui , et comment on procède,  pour faire remonter la mise à jour dans les sources.

**Comment by phgrosjean** [comment]
OK.

**Comment by ChristianWia** [comment]
label Rbug créé pour s'en souvenir

**Comment by ChristianWia** [comment]
signalé et à suivre -> https://bugs.r-project.org/show_bug.cgi?id=18799
