### ISSUE TITLE
{data.table} traduction de "tl of class is marked" ?

### ISSUE THREAD

**Issue by emaigne** [phgrosjean/rfrench#36]
J'ai plusieurs fois "tl of class is marked".
J'ai regardé dans le code source, `tl` ici c'est pour `TRUELENGTH(dt)`. 
Je ne sais pas trop comment traduire le mot "marked" ? marqué ? je ne sais pas si ça a du sens ? fixé ?

**Comment by ChristianWia** [comment]
marqué... mais marquage de quoi ?  peut être le développement sait de quoi il s'agit, lui. Leur demander un message plus explicite si on veut aller plus loin.

**Comment by phgrosjean** [comment]
Je pense que cela a à voir avec la surallocation dans l'objet liste qui constitue la data.table. Mais quelle que soit la traduction, le message reste peu compréhensible (je traduirais simplement par "marqué", ou "tagué", mais ce dernier mot est moins "français").
Dans {data.table} on a pas mal de messages qui ne sont compréhensibles **que** si on lit le code source en C... et encore, si on est aussi issu de la bonne planète :-(. Nous avions eu une petite discussion au début (voir #27) où nos avions décidé de ne pas chercher à interpréter et à expliciter les messages au delà de ce que les auteurs ont voulu faire, avec tout de même quelques abréviations à expliciter telles qu'elles sont mises dans le dictionnaire.
Donc:

```
Internal error, tl of class is marked but tl<0.
```

que je traduirais en :

```
Erreur interne, TRUELENGTH(dt) de la classe est marqué mais est < 0.
```

Et non, je ne comprends pas beaucoup plus ce que cela peut vouloir dire !

**Comment by ChristianWia** [comment]
ici c'est le nom de la variable et il ne doit donc pas être traduit

**Comment by emaigne** [comment]
Fait ! Et j'ai gardé "marqué"
