### ISSUE TITLE
Comment traduire "data.table issue tracker"

### ISSUE THREAD

**Issue by emaigne** [phgrosjean/rfrench#37]
gestionnaire de tickets data.table ?

**Comment by phgrosjean** [comment]
Quand la traduction en français n'est pas forcément évidente à comprendre parce que tout le monde utilise le terme anglais, je mets la version française et je précise le nom anglais entre parenthèse. Donc, j'écrirais "gestionnaire de tickets (issue tracker) de data.table".

**Comment by ChristianWia** [comment]
**ticket** est le bon mot - utilisation courante/commune sur la plupart des systèmes pour matérialiser la déclaration d'une situation à traiter (problème, bogue, demande de fonction ...) . En retour on a un numéro de ticket ou une référence que l'on peut utiliser.

**Comment by emaigne** [comment]
J'ai mis ça : "gestionnaire de tickets (issues tracker) de data.table", je clos l'issue.
