### ISSUE TITLE
typo "corrisponding" dans  transpose.R:74

### ISSUE THREAD

**Issue by ChristianWia** [phgrosjean/rfrench#44]
dans R-fr.po,  typo "**corrisponding**" en ligne 3091; à remplacer par 'corr**e**sponding' dans le source.

#: transpose.R:74
#, c-format
msgid ""
"In the argument 'type.convert', '%s' was ignored because all elements in the transpose list or elements "
"**corrisponding** to indices specified in the 'keep' argument have already been converted."

**Comment by phgrosjean** [comment]
OK, il faudra faire remonter l'info.

**Comment by ChristianWia** [comment]
Le source semble avoir été corrigé depuis ; closed. 

->  https://github.com/Rdatatable/data.table/blob/master/R/transpose.R

        else
          warningf("In the argument 'type.convert', '%s' was ignored because all elements in the transpose list or elements corresponding to indices specified in the 'keep' argument have already been converted.", last_item)
      }
